[package]
name = "ais_simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }


[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tokio-test = "*"